pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                withAWS(role:"jenkins", roleSessionName: "role", useNode: true){
                    sh "aws ec2 run-instances \
    --image-id ami-08766f81ab52792ce \
    --count 1 \
    --instance-type t2.micro \
    --key-name j_key \
    --security-group-ids sg-05e0eaab7ba23bf57 \
    --subnet-id subnet-071874fe08c34005a \
    --block-device-mappings "[{\"DeviceName\":\"/dev/sdf\",\"Ebs\":{\"VolumeSize\":30,\"DeleteOnTermination\":true}}]" \
    --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=demo-server}]' 'ResourceType=volume,Tags=[{Key=Name,Value=demo-server-disk}]'"
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deplying...'
            }
        }
    }
}
